### ISSUE TITLE
Prefer logging over print statements

### ISSUE THREAD

**Issue by jvfe** [lubianat/complex_bot#2]
There are some places in your bot source code where you use printing to provide information on how the bot is running, e.g.:

https://github.com/lubianat/complex_bot/blob/ba92976339ac797f86c2c66ff6383748692f1599/src/utils.py#L108
https://github.com/lubianat/complex_bot/blob/ba92976339ac797f86c2c66ff6383748692f1599/src/utils.py#L180

Though this is a somewhat minor improvement, logging is superior to printing in many aspects, [see this for reference](https://stackoverflow.com/a/6918596/14933331)

I'd be willing to send a pull request refactoring all your print statements into logging statements, if you'd agree.

**Comment by lubianat** [comment]
Sure, that sounds great. Print statements were for quick and dirty debugging and kind of just kept hanging there
